openapi: 3.0.1
info:
  title: HealthCareAPI_payload_funcancat
  description: API Definition of HealthCareAPI_payload_funcancat
  version: 1.0.0
servers:
- url: http://localhost:8290/healthcare
paths:
  /{char}/{word}:
    get:
      parameters:
      - name: char
        in: path
        required: true
        schema:
          type: string
      - name: word
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
