openapi: 3.0.1
info:
  title: MessageTypeTransform
  description: API Definition of MessageTypeTransform
  version: 1.0.0
servers:
- url: http://localhost:8290/Duplicat
paths:
  /:
    get:
      responses:
        default:
          description: Default response
