openapi: 3.0.1
info:
  title: Xslt_Mediator
  description: API Definition of Xslt_Mediator
  version: 1.0.0
servers:
- url: http://localhost:8290/xslt-mediator-example
paths:
  /:
    get:
      responses:
        default:
          description: Default response
