openapi: 3.0.1
info:
  title: Headermedi
  description: API Definition of Headermedi
  version: 1.0.0
servers:
- url: http://localhost:8290/header-part
paths:
  /:
    get:
      responses:
        default:
          description: Default response
