openapi: 3.0.1
info:
  title: EnrichMedi
  description: API Definition of EnrichMedi
  version: 1.0.0
servers:
- url: http://localhost:8290/learnenrich
paths:
  /:
    post:
      responses:
        default:
          description: Default response
